### ISSUE TITLE
wrong use of property name

### ISSUE THREAD

**Issue by wingchiutong** [kristianfreeman/cloudflare-retrieval-augmented-generation-example#2]
https://github.com/kristianfreeman/cloudflare-retrieval-augmented-generation-example/blob/369a38aa70916b0cf71a17ff1aa416149c8877ee/src/index.js#L59

`vec.vectorId should be vec.id`

the expected return of vectorQuery should be 

```
vectorQuery: Object {
  count: 1,
  matches: [
    {
      id: 1,
      score: 0.8645
    }
  ]
}
```

**Comment by kristianfreeman** [comment]
Fixed in recent update. Thanks for opening this issue, sorry for the delay!
